ARDUINO_DIR				= /usr/share/arduino
ARDUINO_PORT			= /dev/ttyACM0
#TARGET					= &lt;your project name&gt;
ARDUINO_LIBS			=
#MCU						= atmega328p
#F_CPU					= 16000000
#AVRDUDE_ARD_BAUDRATE	= 115200
#AVRDUDE_ARD_PROGRAMMER	= arduino

include Arduino.mk
